### ISSUE TITLE
Connection schematics?

### ISSUE THREAD

**Issue by diegoroccia** [jnurkka/Smart_Delonghi#3]
Hi! I was interested to replicate the project on my caffee machine but I can't find the schematics of the connections. Can you provide it? 

Thank you!

**Comment by jnurkka** [comment]
Thanks for your interest @diegoroccia. Unfortunately we never finished this hackathon project, so dont expect to be able to replicate the idea without quite some effort.

I cant provide you with extensive documentation, but if you have some specific questions, I can try to help

**Comment by diegoroccia** [comment]
I was hoping to get a diagram showing how and where did you connect the various GPIO pins to the command board

**Comment by jnurkka** [comment]
Unfortunately we never drew that, sorry :/
